dotnet/source-build-externals

eng/SourceBuild.props
Renamed the source-build intermediate package to align with the new repo name after migrating from dotnet/source-build
Related https://github.com/dotnet/source-build/issues/2625
=> Rename the source-build intermediate package

repos/Directory.Build.targets
In the installer tarball build, we want to remove the `objects` directories from the .gitdirs in order to save space and allow the tarball to be checked into a Git repo itself.  This causes a problem in the specific configuration of a submodule with a redirected .gitdir where the `objects` directory has been deleted - Git will error out attempting to apply patches from that current directory.  This introduces a workaround by setting GIT_DIR to /dev/null, so Git will skip .gitdir discovery and instead treat the submodule directory like any other non-source-controlled directory.  This is acceptable because we just need the patches to be applied.
=> Force skipping .gitdir discovery when patching submodules.

repos/azure-activedirectory-identitymodel-extensions-for-dotnet.proj
https://github.com/dotnet/source-build-externals/pull/28 brought in a couple IdentityModel PRs that needs to be addressed.  The issue is that the packages are built but not getting packaged.
=> Remove source-build prebuilts

repos/jab.proj
The Jab package is missing from the intermediate therefore is causing a prebuilt.
=> Fix incorrect Jab PackagesOutput path

repos/application-insights.proj
The repo's nuget configs are not getting handled correctly by the source-build-externals [logic](https://github.com/dotnet/source-build-externals/blob/main/repos/Directory.Build.targets#L50) to update the NuGet configs to include the source-build specific feeds.  This is blocking https://github.com/dotnet/installer/pull/14261.
=> Specify the NuGetConfigFiles in the Application-Insights repo project

repos/jab.proj
This is needed for offline build to allow the project to build with newer system assemblies.  Source-build adds a NoWarn for NU1603 but it doesn't flow into the individual repos of source-build-externals.
```
/tarball/src/source-build-externals/artifacts/source-build/self/src/src/jab/src/Jab/Jab.csproj : error NU1603: Microsoft.CodeAnalysis.Common 4.4.0 depends on System.Collections.Immutable (>= 7.0.0-rc.1.22367.4) but System.Collections.Immutable 7.0.0-rc.1.22367.4 was not found. An approximate best match of System.Collections.Immutable 7.0.0-rc.1.22403.8 was resolved.
/tarball/src/source-build-externals/artifacts/source-build/self/src/src/jab/src/Jab/Jab.csproj : error NU1603: Microsoft.CodeAnalysis.Common 4.4.0 depends on System.Reflection.Metadata (>= 7.0.0-rc.1.22367.4) but …
```
=> NoWarn NU1603 for Jab

patches/jab/0002-Resolve-RS1031-errors.patch
These errors surfaced in the bootstrap tarball build CI (e.g. build the tarball and then rebuild with the output of the first built).
Microsoft internal CI build link - https://dev.azure.com/dnceng/internal/_build/results?buildId=1966820&view=logs&j=05a957c8-6537-5d6d-69e3-d72786d35c31&t=8f2f8c4f-4a49-5a74-0521-8049d6bde132
=> Add patch to address RS1031 errors in jab

.vsts.pipelines/builds/ci.yml, eng/common/templates/job/source-build.yml, eng/common/templates/job/source-index-stage1.yml
This change is required to continue building PRs in the dotnet public repo.  The agents and images used in the new project / organization are identical and build regressions are not expected.  Updating files under eng/common is intentional to move as much as possible over to viable build agents (normally this is not done).
For questions / concerns, please stop by the .NET Core Engineering Services [First Responders Teams Channel](https://teams.microsoft.com/l/channel/19%3aafba3d1545dd45d7b79f34c1821f6055%40thread.skype/First%2520Responders?groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47).
=> Update public pool names

eng/Versions.props
7.0 work has branched to https://github.com/dotnet/source-build-externals/tree/release/7.0.  Versioning in main needs to be updated to 8.0.
=> Update main versioning to 8.0

.vsts.pipelines/builds/ci.yml, eng/Version.Details.xml, eng/common/build.ps1, eng/common/templates/job/execute-sdl.yml, eng/common/templates/job/onelocbuild.yml, eng/common/templates/job/source-build.yml, eng/common/templates/job/source-index-stage1.yml, eng/common/templates/jobs/jobs.yml, eng/common/templates/jobs/source-build.yml, eng/common/templates/post-build/post-build.yml, global.json
Adjusts .yml files and includes an arcade update from .NET 7 Eng channel to make all builds run in -Svc pools (separate but identical pools for billing purposes)
=> Move to -Svc pools

.vsts.pipelines/builds/ci.yml
This change moves all of the docker images to the latest tag as part of https://github.com/dotnet/arcade/issues/10377.
=> Use latest docker containers

eng/Versions.props, repos/humanizer.proj
When Humanizer was upgraded from 2.2.0 to 2.14.1 in https://github.com/dotnet/source-build-externals/pull/52, the HumanizerCorePackageVersion property was missed.  The result is that the Humanizer NuPkg package version was incorrect.  This was surfaced in the repo-level prebuilt detection work where repos that depend on 2.14.1 were unable to find the version from source-build-externals.  This wasn't an issue in the full product build because of the pvp flow.
I decided to move the version property into the Humanizer repo project to make the repos more self contained.  This would have helped prevent this oversight.
=> Correct Humanizer NuPkg version

repo-projects/MSBuildLocator.proj, repo-projects/cssparser.proj, repo-projects/humanizer.proj
Fixes: https://github.com/dotnet/source-build/issues/2907
=> Build with PublicSign=true by default

patches/application-insights/0001-Eliminate-prebuilts.patch
The current used SHA which maps to 2.20.0 is already flagged as deprecated on nuget.org.
Upgrading to 2.21.0 and then updating the consumers (arcade).
@MichaelSimons @mmitche
=> Update ApplicationInsights to 2.21.0

patches/application-insights/0001-Eliminate-prebuilts.patch
Regressed with https://github.com/dotnet/source-build-externals/commit/d1db09ce5c5a2aeab37d01336765861c0283f76f
Accidentally went too far, up to the latest commit in ApplicationInsights. Instead, we want the 2.21.0 head commit: 5e2e7ddda961ec0e16a75b1ae0a37f6a13c777f5
=> Downgrade ApplicationInsights to 2.21.0

repo-projects/Directory.Build.props
The SDK by default restores transitive targeting packs Microsoft.AspNetCore.App.Ref and Microsoft.WindowsDesktop.App.Ref but provides an opt-out switch `DisableTransitiveFrameworkReferenceDownloads=true`.
As these transitive targeting packs are usually not needed and definitely not for source-build-externals, disabling them via an environment variable so that the setting applies to all external projects in the tree.
=> Remove aspnetcore prebuild from MSBuildLocator and other externals

.gitmodules, .vsts.pipelines/builds/ci.yml, eng/Build.props, eng/NoOp.csproj, eng/SourceBuild.props, patches/abstractions-xunit/0001-Patching.patch, patches/xunit/0001-Patching.patch, repo-projects/abstractions-xunit.proj, repo-projects/xunit.proj
This PR adds xunit and xunit abstractions into source-build-externals. The set of functionality source-built for xunit is relatively limited:
- TFMs are limited to netstandard2.0
- Packages include:
- xunit.core (text only package)
- xunit.abstractions
- xunit.extensibility.core
- xunit.extensibility.execution
- xunit.runner.utility
The changes required for the projects generally centered around:
- Trimming/updating of TFMs
- Removal of automated versioning logic
- Trimming away of the projects to build
In addition to that, I had to make some small tweaks to the way the repo builds. Because xunit depends on xunit.abstractions, to avoid prebuilts we need to introduce a DependencyPackageProjects style 2-phase build.
=> Add xunit 2.4.2 and xunit-abstractions 2.0.3

patches/azure-activedirectory-identitymodel-extensions-for-dotnet/0002-Add-updateAssemblyInfo-bash-script.patch, repo-projects/azure-activedirectory-identitymodel-extensions-for-dotnet.proj
By default IdentityModel assemblies have a version of 0.0.1, which is the default version specified in the [azure-activedirectory-identitymodel-extensions-for-dotnet](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet) repo. This differs from the Microsoft-produced versions of these assemblies that the SDK contains, which has an assembly version of 7.0.0.
This is fixed by explicitly updating the AssemblyInfo.cs file of each source project in the repo to have the desired version attributes. There's already an existing [PowerShell script](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/9aab2749e0ac8a6b8090980c445a559b816f0cf0/updateAssemblyInfo.ps1) which does this. However, that script can't be executed in the …
=> Set correct assembly version for IdentityModel assemblies

patches/azure-activedirectory-identitymodel-extensions-for-dotnet/0002-Add-updateAssemblyInfo-bash-script.patch
The changes from https://github.com/dotnet/source-build-externals/pull/179 are failing in some of the build legs for distros which do not have the `xmllint` tool available. We want to avoid introducing a new package prerequisite from building. So these changes update the script to replace the usage of `xmllint` with `grep`.
=> Remove dependency on xmllint in IdentityModel script

patches/azure-activedirectory-identitymodel-extensions-for-dotnet/0002-Add-updateAssemblyInfo-bash-script.patch
The `-P` option (Perl regular expression syntax) used for the `grep` command in the IdentityModel script patch isn't recognized in the BusyBox version of `grep`. So this fails in Alpine builds.
I've replaced the usage of those `grep` statements to use `sed` instead. This time I've verified these commands work across all distros we use in CI: Alpine, CentOS, Fedora, Ubuntu.
Fixes dotnet/source-build#3590
=> Replace grep with sed in IdentityModel script patch

patches/azure-activedirectory-identitymodel-extensions-for-dotnet/0001-fix-for-source-build.patch, repo-projects/azure-activedirectory-identitymodel-extensions-for-dotnet.proj
Update to 7.0.0-preview3
cc @captainsafia @jennyf19
=> Update Microsoft.IdentityModel dependencies

README.md
Updating the readme to help .NET devs self-service when they need to add new/update components.
=> Update readme with instructions for adding/updating external components

patches/azure-activedirectory-identitymodel-extensions-for-dotnet/0002-Remove-commit-SHA-from-version-string.patch
The changes from https://github.com/dotnet/source-build-externals/pull/198 are causing the following build error when built in the context of a synchronized VMR build leg:
```
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```
This is related to https://github.com/dotnet/source-build/issues/3573. We can't execute `git` commands in the build and don't yet have predefined git info we can use.
=> IdentityModel patch to remove commit SHA

patches/MSBuildLocator/0001-Eliminate-prebuilts.patch, patches/MSBuildLocator/0002-Move-to-net8.patch, repo-projects/MSBuildLocator.proj
Bump MSBuildLocator to the latest release -- it's used by Roslyn. See https://github.com/dotnet/roslyn/pull/69769#issuecomment-1710756082.
=> MSBuildLocator 1.6.1

repo-projects/MSBuildLocator.proj
This is #213 plus a fix to disable package validation, which doesn't make sense for the source-built package (which deliberately changes TFs).
=> MSBuildLocator 1.6.10

patches/application-insights/0002-Remove-WebGrease-from-TPN-2816.patch
Related to https://github.com/microsoft/ApplicationInsights-dotnet/issues/2814. This cleans up the detected licenses for the repos brought in by SBE into the VMR to not include proprietary licenses.
/cc @omajid
=> Patch to remove WebGrease from TPN for app insights

.gitmodules, patches/spectre-console/0001-remove-packagereferences-for-build.patch, repo-projects/spectre-console.proj
MSBuild and the SDK would like to use some of the interactivity and console layout features from Spectre without reinventing the wheel, and a prereq for that is Spectre.Console being part of source build.
This adds the latest package (0.48.0) tags to source build, but specifically just the primary project/package for the Spectre project. This project contains the vast majority of the UI/layout functions and should serve all of our needs.
=> Add Spectre.Console latest (0.48.0) to Source Build 

patches/humanizer/0001-Fix-building-in-a-source-build-context.patch
Related to https://github.com/dotnet/source-build/issues/4037
When the VMR stage 2 build runs now, it has an updated targeting pack version for net8.0: `8.0.1`. Since humanizer is currently configured to build targeting `net8.0`, it causes an attempt to load Microsoft.NETCore.App.Ref.8.0.1 which is a prebuilt:
```
/repos/dotnet/src/source-build-externals/artifacts/sb/src/src/humanizer/src/Humanizer/Humanizer.csproj error NU1102: Unable to find package Microsoft.NETCore.App.Ref with version (= 8.0.1)
- Found 8 version(s) in previously-source-built [ Nearest version: 9.0.0-preview.1.24073.11 ]
- Found 7 version(s) in reference-packages [ Nearest version: 8.0.0 ]
- Found 0 version(s) in source-built
- Found 0 version(s) in prebuilt [/repos/dotnet/src/source-build-externals/artifacts/sb/src/sr …
```
=> Update humanizer to target net9.0

repo-projects/Directory.Build.props
Has no usages. Part of the UB control update.
=> Remove DotNetBuildFromSource env var set

.vsts.pipelines/builds/ci-public.yml, .vsts.pipelines/builds/ci.yml, .vsts.pipelines/guardian/.gdnsuppress
Splits the existing CI pipeline into two separate pipelines:
* ci-public.yml: for public builds - This is the same as the original content except that conditional logic has been removed that was meant to support internal builds.
* ci.yml: for internal builds - Uses the 1ES pipeline template pattern
The SDL stage revealed some credscan errors coming from arcade (eng/common) and various repos defined as submodules in SBE. The Arcade ones will need to be addressed by the Arcade team. For the others, these are external and so not actionable by us. These have all been added as suppressions.
=> Migrate to 1ES pipeline templates

README.md
This Pull Request implements the suggestions from [this discussion](https://github.com/dotnet/source-build-externals/pull/276#discussion_r1518228886) which pointed out the necessity of adding the steps detailed in [this issue comment](https://github.com/dotnet/source-build/issues/4191#issuecomment-1984552053) to the repo's REDME.
More specifically, the steps discuss which actions to take when updating an SBE component that is in a target repo and in Arcade.
=> Add explanation for when a toolset repo has an SBE dependency

repo-projects/Directory.Build.props
Contributes to https://github.com/dotnet/source-build/issues/4011.
@MichaelSimons @ViktorHofer ptal.
cc @omajid
=> Enable DeterministicSourcePaths.

.vsts.pipelines/builds/ci.yml
The `-pt` pool images are deprecated and will be deleted soon. Migrating to the supported image names instead.
=> Migrate off deprecated "pt" pool image

README.md
Closes https://github.com/dotnet/source-build/issues/4286
This PR updates the steps describing the process of updating a component in a Pre-SBE repo. We've found that the most efficient approach is to utilize the existing Version.Details.xml structure. Accordingly, the steps have been updated to include modifying the Version.props and Version.Details.xml files in a Pre-SBE repo.
=> Revise steps for updating a component in a Pre-SBE repo

repo-projects/Directory.Build.props
Rely on submodules/projects to find and use the correct git commit automagically. This is already handled by sourcelink, which uses full git metadata if avaialable or minimal git metadata otherwise.
In fact, it doesn't look like any of the submodules/projects here use git commit info at all, other than humanizer.
src/humanizer/NuSpecs/Humanizer.Core.nuspec includes a `<repository>` element with a `$RepositoryCommit$` variablea but the nupsec inside the built humanizer nupkg doesn't include this element either before or after this change.
[1] https://github.com/dotnet/sourcelink/tree/main/docs#minimal-git-repository-metadata
=> Remove explicit handling of git commits

patches/humanizer/0001-Tfm-updates-and-eliminate-prebuilts.patch
Related to https://github.com/dotnet/source-build/issues/4482
I plan to open an upstream PR to remove NetStandard 1.0.
[Test Build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2503150&view=results) (Microsoft internal link)
=> Remove NetStandard1.0 tfm support from Humanizer

repo-projects/newtonsoft-json.proj
Related to https://github.com/dotnet/source-build/issues/4482
[Test Build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2503206&view=results) (Microsoft internal link)
=> Stop buildinging NewtonSoft.Json for NetStandard1.*

patches/application-insights/0002-Update-System.Diagnostics.DiagnosticSource-to-elimin.patch
Related to https://github.com/dotnet/source-build/issues/4482
I plan to upstream this change once verified.
[Test Build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2503270&view=results) (Microsoft internal link)
=> Eliminate netstandard1.* references from application-insights

eng/Versions.props, patches/xunit/0001-Patching.patch
Updates the xunit version following https://github.com/dotnet/arcade/pull/15170
If you are upgrading the version of a repo submodule, please follow this
checklist:
the upgrade. Both this PR and the PR doing the upgrade in the consuming repo
should link to that issue.
in the consuming repo in a timely manner? If consuming the dependency flow of
this update takes a long time or needs to be backed out, it may require the
reversion of the upgrade in this PR. That's something we want to avoid.
version upgrade, consider using a separate PR or at least changing the title of
the dependency flow PR to accurately reflect the purpose of the change. Seeing
a PR named "Upgrade IdentityModel to 8.0.1", for example, provides better
clarity than "Update dependencies from dotnet/source-build-externals".
=> Update xunit to 2.9.2

eng/Versions.props
```
.packages/microsoft.dotnet.arcade.sdk/9.0.0-beta.24509.3/tools/SourceBuild/AfterSourceBuild.proj#L81
.packages/microsoft.dotnet.arcade.sdk/9.0.0-beta.24509.3/tools/SourceBuild/AfterSourceBuild.proj(81,5): error : (NETCORE_ENGINEERING_TELEMETRY=AfterSourceBuild) 1 new pre-builts discovered! Detailed usage report can be found at /__w/1/s/artifacts/sb/prebuilt-report/baseline-comparison.xml.
See https://aka.ms/dotnet/prebuilts for guidance on what pre-builts are and how to eliminate them.
Package IDs are:
Microsoft.VisualStudio.SolutionPersistence.1.0.9
```
error from https://github.com/dotnet/msbuild/pull/10794
=> Update vs-solutionpersistence to 1.0.9

patches/xunit/0001-Patching.patch
This was accidentally missed in https://github.com/dotnet/source-build-externals/pull/391
If you are upgrading the version of a repo submodule, please follow this
checklist:
the upgrade. Both this PR and the PR doing the upgrade in the consuming repo
should link to that issue.
in the consuming repo in a timely manner? If consuming the dependency flow of
this update takes a long time or needs to be backed out, it may require the
reversion of the upgrade in this PR. That's something we want to avoid.
version upgrade, consider using a separate PR or at least changing the title of
the dependency flow PR to accurately reflect the purpose of the change. Seeing
a PR named "Upgrade IdentityModel to 8.0.1", for example, provides better
clarity than "Update dependencies from …
=> Remove System.Reflection.TypeExtensions from xunit patch

eng/Versions.props
Fixes https://github.com/dotnet/source-build/issues/4670.
Mirror of the [same change in SBRP](https://github.com/dotnet/source-build-reference-packages/pull/1070).
=> Drop prerelease version label

eng/Versions.props
this has a fix for `dotnet sln remove` command (which isn't yet switched to vs-solutionpersistence)
@edvilme
=> Update vs-solutionpersistence to 1.0.26

eng/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/Microsoft.DotNet.SourceBuild.Tasks.XPlat.csproj
Changes in https://github.com/dotnet/source-build-externals/pull/404 caused a build break.
`/mnt/vss/_work/1/s/artifacts/sb/src/artifacts/obj/Microsoft.DotNet.SourceBuild.Tasks.XPlat/Release/Microsoft.DotNet.SourceBuild.Tasks.XPlat.AssemblyInfo.cs(15,59): error CS7035: The specified version string '10.0.560201.0' does not conform to the recommended format - major.minor.build.revision [/mnt/vss/_work/1/s/artifacts/sb/src/eng/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/Microsoft.DotNet.SourceBuild.Tasks.XPlat.csproj]`
I disabled `GenerateAssemblyInfo` on the tasks project since it doesn't seem necessary for a msbuild task assembly used within the build.
=> Workaround CS7034 build break

patches/humanizer/0001-Tfm-updates-and-eliminate-prebuilts.patch
Attempting to source build this repo with a new build of the .NET 10 SDK causes this error: 
```
CSC : error CS0006: Metadata file '/repos/dotnet/src/source-build-externals/artifacts/sb/package-cache/microsoft.netcore.app.ref/9.0.0/analyzers/dotnet/cs/Microsoft.Interop.ComInterfaceGenerator.dll' could not be found [/repos/dotnet/src/source-build-externals/artifacts/sb/src/src/humanizer/src/Humanizer/Humanizer.csproj::TargetFramework=net9.0]
CSC : error CS0006: Metadata file '/repos/dotnet/src/source-build-externals/artifacts/sb/package-cache/microsoft.netcore.app.ref/9.0.0/analyzers/dotnet/cs/Microsoft.Interop.JavaScript.JSImportGenerator.dll' could not be found [/repos/dotnet/src/source-build-externals/artifacts/sb/src/src/humanizer/src/Humanizer/Humanizer.csproj::TargetFramework=net9.0] …
```
=> Update humanizer to target net10.0

eng/SourceBuildPrebuiltBaseline.xml, eng/Version.Details.xml, eng/Versions.props, patches/azure-activedirectory-identitymodel-extensions-for-dotnet/0001-fix-for-source-build.patch, repo-projects/docker-creds-provider.proj, repo-projects/docker-creds-provider.targets
Fixes #https://github.com/dotnet/source-build/issues/4752
- Update docker-cred-provider to update STJ from 6.0.0 to 8.0.5
- Update azure-activedirectory-identitymodel-extensions-for-dotnet patch to update STJ from 8.0.4 to 8.0.5
- Define darc dependency on MsBuild package to keep the package up-do-date.  This is what brought in the vulnerable System.Formats.Asn1.7.0.0 package.
=> Update vulnerable packages

eng/SourceBuildPrebuiltBaseline.xml, eng/Version.Details.xml, eng/Versions.props, patches/azure-activedirectory-identitymodel-extensions-for-dotnet/0001-fix-for-source-build.patch, repo-projects/docker-creds-provider.proj, repo-projects/docker-creds-provider.targets
Backport of https://github.com/dotnet/source-build-externals/pull/423 to release/9.0
=> [release/9.0] Update vulnerable packages

.gitmodules, Directory.Build.props, build.sh, eng/Build.props, eng/Version.Details.xml, eng/Versions.props, eng/tasks/Directory.Build.props, eng/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/Microsoft.DotNet.SourceBuild.Tasks.XPlat.csproj, eng/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/UpdateJson.cs, repo-projects/Directory.Build.targets, repo-projects/docker-creds-provider-2.2.0.proj, repo-projects/docker-creds-provider.proj, repo-projects/docker-creds-provider.targets
Consolidate/update the 2 docker-creds-provider version to 2.2.4.  This required backporting all of the [infrastructure added](https://github.com/dotnet/source-build-externals/pull/248) to main/9.0 to support updating repo global.json files.
Related to https://github.com/dotnet/source-build/issues/4752
=> Update docker-creds-provider to address vulnerable system.text.json dependency.

NuGet.config
Fixes #https://github.com/dotnet/source-build/issues/4672
I did not add https://github.com/dotnet/arcade/blob/5d30877b1eb318583acd5f2cd3f3a80e77b3add2/Directory.Build.props#L17-L18 because this would need to flow to the external repos in order to have an effect.  Repo patches would be needed for this.  I am of the opinion that we enable this and adjust if necessary.
=> Enable NuGet Audit

eng/Versions.props
Updates vs-solutionpersistence to new release [v.1.0.52](https://github.com/microsoft/vs-solutionpersistence/releases/tag/v1.0.52) with several bug fixes and improvements.
https://github.com/dotnet/sdk/issues/47297
If you are upgrading the version of a repo submodule, please follow this
checklist:
the upgrade. Both this PR and the PR doing the upgrade in the consuming repo
should link to that issue.
in the consuming repo in a timely manner? If consuming the dependency flow of
this update takes a long time or needs to be backed out, it may require the
reversion of the upgrade in this PR. That's something we want to avoid.
version upgrade, consider using a separate PR or at least changing the title of
the dependency flow PR to accurately reflect the purpose of the change. Seeing
a PR named …
=> Update vs-solutionpersistence to 1.0.52

.vsts.pipelines/builds/ci.yml
Follow-up on d795fb17a0354099869692faaeafc3615c52a1d0 which removed the publish action from the source-build template. Make the official build an assetless build so that source changes flow into the VMR.
I mimicked https://github.com/dotnet/scenario-tests/commit/b77639a6d33c9a69cfcd3272ab4f8767d7ae02ea
=> Use assetless build for official build

.config/CredScanSuppressions.json
https://github.com/dotnet/source-build-externals/pull/484 moved the repos but the CredScanSuppressions.json wasn't updated.
=> Fix paths in CredScanSuppressions.json

CODE-OF-CONDUCT.md
This adds back the code of conduct removed in https://github.com/dotnet/source-build-externals/pull/501.  The dotnet org policy requires this.
=> Add back code of conduct
