dotnet/source-build-externals

eng/SourceBuildPrebuiltBaseline.xml, eng/Version.Details.xml, patches/application-insights/0001-Eliminate-prebuilts.patch, repos/application-insights.proj
~~This is blocked on https://github.com/dotnet/source-build-reference-packages/pull/378~~
This is needed because the sdk upgraded their App-Insights reference.
=> Update Application-Insights to 2.19.0

.gitmodules, patches/azure-activedirectory-identitymodel-extensions-for-dotnet/0001-fix-for-source-build.patch, repos/azure-activedirectory-identitymodel-extensions-for-dotnet.proj
Add System.IdentityModel.Tokens.Jwt and dependencies to resolve https://github.com/dotnet/aspnetcore/issues/42599
=> Add System.IdentityModel.Tokens.Jwt and dependencies

patches/humanizer/0001-Fix-building-in-a-source-build-context.patch
Cherry picking https://github.com/dotnet/source-build-externals/pull/51 to main.
=> Update Humanizer to 2.14.1

patches/MSBuildLocator/0001-Eliminate-prebuilts.patch, repos/MSBuildLocator.proj
Fixes https://github.com/dotnet/source-build/issues/3126
=> Update MSBuildLocator to 1.5.5

.config/tsaoptions.json
Fixes https://github.com/dotnet/source-build/issues/3143.
=> Add TsaOptions for component governance alerts.

repo-projects/xunit.proj
xunit.extensibility.execution was missed in the switch over to batching
=> Add missing package

repo-projects/azure-activedirectory-identitymodel-extensions-for-dotnet.proj
This was missed in https://github.com/dotnet/source-build-externals/pull/198
@mthalman @MichaelSimons
=> Fixup for IdentityModel preview4

patches/azure-activedirectory-identitymodel-extensions-for-dotnet/0001-fix-for-source-build.patch, repo-projects/azure-activedirectory-identitymodel-extensions-for-dotnet.proj
cc @MichaelSimons @mthalman @jennyf19
=> Update azure-activedirectory-identitymodel-extensions-for-dotnet to 7.0.0-preview5

repo-projects/MSBuildLocator.proj
=> [8.0] MSBuildLocator 1.6.10

.vsts.pipelines/builds/ci-public.yml, .vsts.pipelines/builds/ci.yml, .vsts.pipelines/guardian/.gdnsuppress
Backport of https://github.com/dotnet/source-build-externals/pull/274
[Test run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2412232&view=results) (internal link)
=> Migrate to 1ES pipeline templates

eng/Versions.props
Related to https://github.com/dotnet/source-build/issues/4482
This removes the following transitive NetStandard1.* package references:
System.Buffers/4.3.0 netstandard1.1 /artifacts/sb/src/artifacts/obj/Microsoft.DotNet.SourceBuild.Tasks.XPlat/project.assets.json
System.Collections/4.3.0 netstandard1.3 /artifacts/sb/src/artifacts/obj/Microsoft.DotNet.SourceBuild.Tasks.XPlat/project.assets.json
System.Collections.Concurrent/4.0.12 netstandard1.3 /artifacts/sb/src/artifacts/obj/Microsoft.DotNet.SourceBuild.Tasks.XPlat/project.assets.json
System.Collections.Immutable/1.3.1 netstandard1.0 /artifacts/sb/src/artifacts/obj/Microsoft.DotNet.SourceBuild.Tasks.XPlat/project.assets.json
System.Diagnostics.Debug/4.3.0 netstandard1.3 /artifacts/sb/src/artifacts/obj/Microsoft.DotNet.SourceBuild.Tasks.XP …
=> Update msbuild version to eliminate NetStandard1.* references

eng/Versions.props
The release/9.0 branch was created now that 9.0 is entering RC. main is now for 10 development so the version was updated.
=> Branding updates for 10

.vsts.pipelines/builds/ci.yml
This is required compliance item.
=> Enable policheck

NuGet.config
6 and 7 replaced with 9 and 10
=> update feed links in nuget.config

.gitmodules, eng/Versions.props, repo-projects/vs-solutionpersistence.proj
combined backport of:
* https://github.com/dotnet/source-build-externals/pull/386
* https://github.com/dotnet/source-build-externals/pull/392
* https://github.com/dotnet/source-build-externals/pull/409
* https://github.com/dotnet/source-build-externals/pull/413
needed by https://github.com/dotnet/sdk/pull/45408
@edvilme
=> Backport vs-solutionpersistence to release/9.0

eng/Versions.props
=> [release/9.0] Update vs-solutionpersistence to 1.0.28

eng/Versions.props
bugfix https://github.com/microsoft/vs-solutionpersistence/pull/83
@JanKrivanek @edvilme
=> Update vs-solutionpersistence to 1.0.28

eng/Versions.props
=> Update vs-solutionpersistence to 1.0.52

.vsts.pipelines/builds/ci.yml
=> Enable binskim

eng/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/UpdateJson.cs, repo-projects/Directory.Build.targets, repo-projects/newtonsoft-json.proj, repo-projects/vs-solutionpersistence.proj
Review by commits and see commit description
=> Follow up on sbe infra improvements
